"""
app/state.py — YogaSutra Shared Session State (Blackboard)

Pydantic models for the ADK session state shared across all agents.
This is the single source of truth for a given YogaSutra run.

Architecture note: the session state acts as the "blackboard" in our
multi-agent communication model (PLAN.md §9.3). Every agent reads from
and writes to this shared structure via ADK session state.
"""
from __future__ import annotations

import uuid
from datetime import datetime, UTC
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class ExperienceLevel(str, Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class PracticeGoal(str, Enum):
    RELAXATION = "relaxation"
    FLEXIBILITY = "flexibility"
    STRENGTH = "strength"
    MEDITATION = "meditation"
    BALANCE = "balance"
    GENERAL = "general"


class RequestMode(str, Enum):
    PRACTICE = "practice"
    KNOWLEDGE = "knowledge"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------


class UserProfile(BaseModel):
    """Structured user profile extracted by the Profile Agent."""

    experience_level: ExperienceLevel = ExperienceLevel.BEGINNER
    available_duration_minutes: int = 20
    preferred_time: str = "morning"
    goal: PracticeGoal = PracticeGoal.RELAXATION
    constraints: list[str] = Field(default_factory=list)
    preferences: list[str] = Field(default_factory=list)

    model_config = {"use_enum_values": True}


class EvidenceChunk(BaseModel):
    """A single retrieved knowledge chunk from the RAG pipeline."""

    chunk_id: str
    document_id: str
    title: str
    section: str
    topic: str
    content: str
    source_type: str = "reference"
    license: str = "curated"
    relevance_score: float = 1.0


class PoseItem(BaseModel):
    """A single pose/activity in a practice sequence."""

    name: str
    sanskrit_name: str = ""
    duration_minutes: int
    instructions: str = ""
    modifications: str = ""
    evidence_chunk_ids: list[str] = Field(default_factory=list)


class PracticePlan(BaseModel):
    """Structured practice plan generated by the Planner Agent."""

    goal: str
    duration_minutes: int
    intensity: str
    sequence: list[PoseItem]
    rationale: str
    evidence_sources: list[str] = Field(default_factory=list)
    expected_outcome: str = ""


class TraceStep(BaseModel):
    """A single step in the execution trace."""

    agent: str
    action: str
    input_summary: str = ""
    output_summary: str = ""
    tools_called: list[str] = Field(default_factory=list)
    latency_ms: float = 0.0
    token_usage: dict[str, int] = Field(default_factory=dict)
    timestamp: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())
    status: str = "success"


# ---------------------------------------------------------------------------
# Main session state
# ---------------------------------------------------------------------------


class YogaSessionState(BaseModel):
    """
    Shared blackboard for the YogaSutra multi-agent system.

    Populated incrementally as each agent completes its work:
      1. Root Agent populates: run_id, session_id, user_input, request_mode
      2. Profile Agent populates: user_profile
      3. Knowledge Agent populates: retrieved_evidence
      4. Planner Agent populates: candidate_plan, final_response
      5. (Phase 2) Safety Agent populates: validation_results
      6. (Phase 2) Critic Agent populates: critique, revision_count
    """

    # Identity
    run_id: str = Field(default_factory=lambda: f"run_{uuid.uuid4().hex[:8]}")
    session_id: str = ""
    persona_id: str = "P00"

    # Request
    user_input: str = ""
    request_mode: RequestMode = RequestMode.UNKNOWN

    # Agent outputs (populated sequentially)
    user_profile: UserProfile | None = None
    retrieved_evidence: list[EvidenceChunk] = Field(default_factory=list)
    candidate_plan: PracticePlan | None = None

    # Phase 2+ fields (declared here for schema completeness)
    validation_results: dict[str, Any] = Field(default_factory=dict)
    critique: str | None = None
    revision_count: int = 0

    # Final
    final_response: str | None = None

    # Observability
    agents_called: list[str] = Field(default_factory=list)
    execution_trace: list[TraceStep] = Field(default_factory=list)
    total_latency_ms: float = 0.0
    start_time: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())

    model_config = {"use_enum_values": True}
